# Generated by Django 3.2.9 on 2021-12-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('avatar', models.ImageField(upload_to='')),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
