# Generated by Django 3.2.9 on 2021-12-06 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя категории')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivery', models.BooleanField()),
                ('address', models.CharField(max_length=255)),
                ('is_order', models.BooleanField()),
                ('date_of_order', models.DateTimeField()),
                ('purchase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('is_in_stock', models.BooleanField(verbose_name='В наличии')),
                ('num_of_item', models.PositiveIntegerField(verbose_name='Количество в наличии')),
                ('days_for_production', models.PositiveIntegerField(verbose_name='Дней для изготовления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('product_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('num_of_products', models.PositiveIntegerField(default=1, verbose_name='Кол-во изделий')),
                ('final_price', models.PositiveIntegerField(verbose_name='Общая цена')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_item', models.PositiveIntegerField(verbose_name='Кол-во')),
                ('date_of_order', models.DateTimeField(verbose_name='Дата заказа')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='Заказ')),
                ('order_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.orderstage', verbose_name='Стадия заказа')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer', verbose_name='Покупатель')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.PositiveIntegerField(verbose_name='Общая цена')),
                ('is_active', models.BooleanField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('products', models.ManyToManyField(blank=True, to='shop.ProductInCart')),
            ],
        ),
    ]
