# Generated by Django 3.2.9 on 2021-12-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'История заказов', 'verbose_name_plural': 'История заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderstage',
            options={'verbose_name': 'Стадия заказа', 'verbose_name_plural': 'Стадии заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Стадия заказа'),
        ),
    ]
