# Generated by Django 3.2.9 on 2021-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Review', verbose_name='Отзывы'),
        ),
    ]
