# Generated by Django 3.2.9 on 2021-12-13 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
