# Generated by Django 3.2.9 on 2021-12-13 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211213_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
