# Generated by Django 3.2.9 on 2021-12-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='item_id',
            new_name='product_id',
        ),
    ]
